version: "3.5"

services:
  server:
    image: ghcr.io/animo/openid4vc-playground-funke/agent:main
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == community
      labels:
        traefik.enable: "true"

        traefik.http.routers.openid4vc-server.rule: Host(`funke.animo.id`) && (PathPrefix(`/api`) || PathPrefix(`/oid4vci`) || PathPrefix(`/oid4vp`) || PathPrefix(`/provider`) || PathPrefix(`.well-known`))
        traefik.http.routers.openid4vc-server.entrypoints: web-secure
        traefik.http.routers.openid4vc-server.tls.certresolver: zerossl
        traefik.http.routers.openid4vc-server.service: openid4vc-server-service
        traefik.http.services.openid4vc-server-service.loadbalancer.server.port: 3001

    environment:
      AGENT_WALLET_KEY: ${AGENT_WALLET_KEY}
      P256_SEED: ${P256_SEED}
      X509_CERTIFICATE: ${X509_CERTIFICATE}
      AGENT_HOST: "https://funke.animo.id"
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}

    networks:
      - traefik

    ports:
      - 5001

  client:
    image: ghcr.io/animo/openid4vc-playground-funke/app:main
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == community
      labels:
        traefik.enable: "true"
        traefik.http.routers.openid4vc-app.rule: Host(`funke.animo.id`) && !PathPrefix(`/oid4vci`) && !PathPrefix(`/oid4vp`) && !PathPrefix(`/api`) && !PathPrefix(`/provider`)
        traefik.http.routers.openid4vc-app.entrypoints: web-secure
        traefik.http.routers.openid4vc-app.tls.certresolver: zerossl
        traefik.http.routers.openid4vc-app.service: openid4vc-app-service
        traefik.http.services.openid4vc-app-service.loadbalancer.server.port: 80
      update_config:
        monitor: 30s
        delay: 10s
        order: start-first
    ports:
      - 80
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik
